### ISSUE TITLE
False positive with QApplication::translate

### ISSUE THREAD

**Issue by SebastianJaworowicz** [Blake-Madden/i18n-check#4]
Hello,

I found false positive when using QApplication::translate, used HEAD sources.

code sample test.cpp
```
QString test = qApp->translate("SomeContex", "source");
QString test = QApplication::translate("SomeContex", "source");
```

Checker output test.txt
```
File	Line	Column	Value	Explanation	WarningID
test.cpp	2	41	"SomeContex"	String available for translation that probably should not be in function call: QApplication::translate	[suspectL10NString]
```

Startup parameters
`i18n-check.exe -o test.txt -v --disable unencodedExtASCII test.cpp`

**Comment by Blake-Madden** [comment]
Thanks for checking out the program!

Looks like I'm not taking `QApplication::translate` being called statically in account, should be an easy fix. I'll have something shortly.

Also, I'm about to check in a change that turns `unencodedExtASCII` off by default, so you won't need to explicitly disable it anymore. It seemed a little too pedantic to include by default the more I thought about it.

**Comment by SebastianJaworowicz** [comment]
Thank you for quick fix, I see you hard coding every function so, `QApplication::tr` and `QApplication::trUtf8` should be also added.

**Comment by Blake-Madden** [comment]
Oh, good point. Thanks, I'll get those fixed.
